---
title: "Série _Introdução às Bases da Estatística Bayesiana_"
subtitle: |
    _Live_ 1/6: 
      Apresentando a Estatística Bayesiana
author: |
    Prof. Dr. Marcelo Ventura Freire (EACH/USP)
    <https://github.com/zyxdef/BayesLives>
date: "16/03/2020"
output: 
  beamer_presentation:
      # keep_tex: yes
      keep_tex: no
header-includes:
  - \usepackage{enumitem}
  - \usepackage{tikzsymbols}
  - \setlistdepth{20}
  - \renewlist{itemize}{itemize}{20}
  - \renewlist{enumerate}{enumerate}{20}
  - \setlist[itemize]{label=$\cdot$}
  - \setlist[itemize,1]{label=*}
  - \setlist[itemize,2]{label=\textbullet}
  - \setlist[itemize,3]{label=--}
  - \setlist[itemize,4]{label=$\cdot$}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Objetivos desta série de _lives_

O objetivos desta série de 6 _lives_ é dar uma visão panorâmica àquilo que dá a 
base, que dá o fundamento à Estatística Bayesiana, mas sem se pretender ser um
tutorial de uso e nem um curso teórico, pois não disporíamos de tempo o suficiente
para nenhum dos dois.

- O tutorial fica para a próxima série. $\Winkey$

- O repositório deste material está em <https://github.com/zyxdef/BayesLives>


# Exemplos de aplicação

## **PRÉ-ROTEIRIZAÇÃO** $\longrightarrow$ **Lembrar de tirar daqui**

Apresentação de 3 exemplos que motivarão e serão usados para ilustrar as _lives_ 
seguintes. 

- para cada exemplo, apresentaremos uma situação em que é preciso apresentar 
  - informação sobre o contexto da situação
    - afinal, toda análise é estritamente condicionada no contexto de onde 
      seus dados vieram
    - quais conceitos e definições devem ser usados?
    - quais pressuposições podem ser assumidas a respeito 
      - do que observamos?
      - do que *não* observamos?
    - qual é a natureza dos dados a serem trabalhados?
      - importa como, quando e em que ordem eles foram coletados?
      - se sim, quais são as respostas a essas perguntas?
    - em suma, não se faz análise em um vácuo de contexto (viu, ML e IA)

---

- para cada exemplo, apresentaremos uma situação em que é preciso apresentar 
  - qual é a necessidade de informação?
    - algum aspecto essa situação é desconhecida
    - quem precisa dessa informação?
    - de qual informação essa pessoa precisa?
    - qual o nível de detalhamento é necessário?
  - dados observados
    - apresentados parcial ou totalmente, em forma tabular 
  - nome do método bayesiano adequado para lidar com o problema
  - conclusão obtida para a necessidade de informação com a aplicação 
    desse método nesses dados

---

- idealmente, os exemplos terão grau crescente de complexidade 
  - simprão, simples e médio ?  
  - sem difícil; nada de modelos hierárquicos ou de BSEM
- idealmente, serão exemplos vindos de áreas distintas
  - ?? saúde pública
  - ?? marketing
  - ?? engenharia
- idealmente, os métodos cobrirão tipos diferentes de dados
  - respostas dummy,contagem e contínua
  - regressoras categóricas e quantitativas



## Exemplo 1: nível *very easy*

- contexto da situação
- necessidade de informação
- dados observados
- método adequado para lidar com o problema
- conclusão obtida



## Exemplo 2: nível *easy*

- contexto da situação
- necessidade de informação
- dados observados
- método adequado para lidar com o problema
- conclusão obtida



## Exemplo 3: nível *moderate*

- contexto da situação
- necessidade de informação
- dados observados
- método adequado para lidar com o problema
- conclusão obtida


## Exemplo 4: nível *hard* -- nosso modelo de cognição musical

- contexto da situação
  - como lidamos com material como melodias?
  - ***VER MAIS NO RELATÓRIO DA FAPESP***
  - variáveis observáveis e variáveis latentes ligando as variáveis observáveis
  - diversos domínios não observáveis diretamente (variáveis latentes):
    - produção vocal
    - percepção auditiva
    - integração sensório-motora
    - memória operacional (working memory)
  - coleta de dados (variáveis observáveis)
    - tanto com instrumentos já consolidados como com instrumentos desenvolvidos 
      na pesquisa
    - escalas ordinais, dados de contagem e medidas contínuas
- necessidade de informação
  - o grau de habilidade de cada respondente em cada domínio em função das suas
    respostas no conjunto de instrumentos aplicados
  - o grau de influência de cada domínio em cada instrumento separadamente
  - avaliação da adequação dos instrumentos propostos
- dados observados
- método adequado para lidar com o problema
  - modelo hierárquico Bayesiano com modelagens diferentes para cada instrumento 
    em função do tipo de variáveis que observou
  - mas com as variáveis latentes por trás da associação (correlação) entre as
    variáveis dos diferentes instrumentos
- conclusão obtida
  - ***VER NO RELATÓRIO DA FAPESP***
- este último exemplo ilustra bem o potencial de utilização dos métodos Bayesianos 
  em contexto complicados de abordar 



## O que é Estatística Bayesiana?

Respondendo de uma forma enganadoramente simples, _Estatística Bayesiana_ é uma 
forma lógica e quantitativamente coerente de decidir em que escolher acreditar 
ou escolher como agir em face aos dados observados

- Porquê "enganadoramente simples"?
  - É o que vamos ver nos próximos 5 _slides_ e também nas próximas 5 *lives*

---
  
- a partir de um estado inicial de baixo conhecimento a respeito do fenômeno, 
  assumir uma crença difusa a seu respeito, coletar observações e atualizar 
  a crença de forma coerente em face ao que tiver sido observado
- essa escolha racional de crença ou expectativa sobre a realidade será 
  caracterizada quantitativamente na forma de *Probabilidade*, 
  tema da nossa **2^a^ _live_**

---

- mais detalhadamente: 
  - crença inicial (chamada *probabilidade a priori*)
    - anterior à coleta dos dados
    - vaga, difusa, imatura e incerta
  - crença atualizada pelos dados (chamada *probabilidade a posteriori*)
    - posterior à coleta dos dados
    - menos vaga, mais concentrada, mais madura e menos incerta
- esse processo de atualização da crença em função dos dados observados será
  realizado através de um mecanismo chamado _Teorema de Bayes_,
  tema da nossa **3^a^ _live_**
  
---
  
- de posse dessa crença final, é possível começar a responder a necessidade
  de informação sobre a realidade; mas é preciso antes saber caracterizar
  quantitativamente o tipo de necessidade de informação para usar essa crença;
  é aqui que entram a _Teoria da Decisão_ e a _Inferência Bayesiana_,
  temas da nossa **4^a^ _live_**
  
---
  
- exceto em raras situações triviais, não será possível encontrar uma solução 
  analítica com aplicação de fórmulas matemáticas explícitas nos dados, 
  de modo que é preciso usar outra forma de calcular as respostas 
  às necessidades de informações; nesse ponto, falaremos dos métodos 
  computacionais que permitirão chegar às respostas, 
  o que será o tema da **5^a^ _live_**

---

- por fim, na nossa **6^a^ e última _live_**, retomaremos os 3 exemplos 
  desta 1^a^ _live_ e vamos realizar a análise completa para cada um:
  - modelar os dados a partir do contexto e necessidade de informação apresentados
  - usar os programas R e JAGS para encontrar a resposta Bayesiana
  - levar de volta essa resposta ao contexto original, interpretando-a
